language: php
sudo: false
php:
  - '7.0'

services:
  - mysql

before_install:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --configuration phpunit.dist.xml --coverage-clover=builds/coverage/clover.xml test

after_script:
  - php vendor/bin/php-coveralls -v